---
output: html_document
---

# Exercício (AmesHousing)

1. Ajuste um modelo de regressão para o banco de dados 'AmesHousing'.

2. Ajuste também um modelo de regressão com regularização.

```{r}
library(tidyverse)
library(AmesHousing)
library(recipes)
library(caret)

ames <- make_ames()
glimpse(ames)
ames$Sale_Price
```

Regressão

```{r}
receita <- recipe(Sale_Price ~ ., data = ames) %>%
  step_dummy(all_nominal()) %>%
  step_nzv(all_predictors()) %>%
  step_corr(all_predictors())

set.seed(20032019)

modelo <- train(
  receita, 
  ames, 
  method = "lm",
  trControl = trainControl(method = "cv", number = 5)
)

modelo

```

```{r}
ames %>% 
  mutate(pred = predict(modelo, ames)) %>% 
  ggplot(aes(y = pred, x = Sale_Price)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue") +
  theme_bw()
```

Regressão com regularização

```{r}
receita <- recipe(Sale_Price ~ . , data = ames) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_nzv(all_predictors()) %>%
  step_corr(all_predictors()) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())

modelo <- train(
  receita, 
  ames, 
  method = "glmnet", 
  trControl = trainControl(method = "cv", number = 5)
)

modelo
```

```{r}
tune_grid <- expand.grid(
  alpha = 0.1, 
  lambda = seq(50, 500, 50)
)

modelo <- train(
  receita, 
  ames, 
  method = "glmnet", 
  trControl = trainControl(method = "cv", number = 5),
  tuneGrid = tune_grid,
  lambda = seq(50, 500, 50)
)

modelo
```

```{r}
ames %>% 
  mutate(pred = predict(modelo, ames)) %>% 
  ggplot(aes(y = pred, x = Sale_Price)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "blue") +
  theme_bw()
```

# Exercício

Ajuste um modelo de regressão logística p/ prever o churn de funcionários no banco de dados `attrition`.

```{r}
library(rsample)

data(attrition, package = "rsample")
glimpse(attrition)

attrition %>% 
  count(Attrition) %>% 
  mutate(prop = n/sum(n))
```

```{r}
attrition <- attrition %>% 
  mutate(Attrition = forcats::lvls_reorder(Attrition, c(2,1)))

receita <- recipe(Attrition ~ ., data = attrition) %>%
  step_meanimpute(all_numeric(), -all_outcomes()) %>%
  step_modeimpute(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_corr(all_predictors()) %>%
  step_nzv(all_predictors())

metricas <- function(data, lev = NULL, model = NULL) {
  c(
    defaultSummary(data, lev, model), 
    twoClassSummary(data, lev, model)
  )
}

train_control <- trainControl(
  method = "cv", 
  number = 5, 
  classProbs = TRUE,
  summaryFunction = metricas,
  savePredictions = TRUE
)

modelo <- train(
  receita, 
  attrition, 
  method = "glm", 
  family = "binomial", 
  trControl = train_control
)

modelo
```

```{r}
attrition %>% 
  mutate(pred = predict(modelo, attrition)) %>% 
  select(Attrition, pred) %>% 
  table
```






