---
title: "Random Forest e XGBoost"
output: html_notebook
---

```{r}
library(tidyverse)
library(AmesHousing)
library(recipes)
library(caret)
library(randomForest)
library(xgboost)
library(pROC)
```

# Data prep

```{r}
data("credit_data")

set.seed(1)
linhas_de_treino = runif(nrow(credit_data)) < 0.8
credit_data$base = if_else(linhas_de_treino, "treino", "teste")

credit_data_treino <- credit_data %>% filter(base == "treino") %>% select(-base)
credit_data_teste <-  credit_data %>% filter(base == "teste") %>% select(-base)

receita <- recipe(Status ~ ., data = credit_data_treino) %>%
  step_meanimpute(all_numeric(), -all_outcomes()) %>%
  step_modeimpute(all_nominal(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_corr(all_predictors()) %>%
  step_nzv(all_predictors())
```







# Random Forest 

```{r}
train_control_rf <- trainControl(
  method = "cv", 
  number = 5, 
  classProbs = TRUE,
  summaryFunction = twoClassSummary,
  verboseIter = 1
)

# DICA: rode
# info <- getModelInfo("rpart", FALSE)$rpart
# info$parameters

grid_rf <- data.frame(
  mtry = c(2, 3, 4, 5, 6, 7)# PREENCHA AQUI
)

modelo_rf <- train(
  receita, 
  credit_data_treino, 
  method =, #PREENCHA AQUI
  metric = "ROC",
  trControl = train_control_rf,
  tuneGrid = grid_rf
)
```

## Resultado
```{r}
modelo_rf
modelo_rf$bestTune
varImp(modelo_rf)
plot(modelo_rf)
```

```{r}
# Matriz de confusão
credit_data_teste <- credit_data_teste %>% mutate(pred_rf = predict(modelo_rf, ., type = "prob")$bad)
caret::confusionMatrix(predict(modelo_rf, credit_data_teste), credit_data_teste$Status)
```

```{r}
#curva ROC
roc_rf <- roc(credit_data_teste$Status, credit_data_teste$pred_rf)
ggroc(roc_rf)
```

```{r}
# área sob a curva ROC
# auc(roc_rpart)
auc(roc_rf)
```





# XGBoost

Exercício: Ajuste um xgboost usando o caret e responda: qual modelo apresenta a maior AUC? crtl+C ctrl+V por sua conta!

DICA 1) troque "rf" por "xgbTree"
DICA 2) rode `info <- getModelInfo("rpart", FALSE)$rpart` e depois consulte `info$parameters`.
DICA 3) experimente usar o parâmetro `tuneLength` em vez do ``tuneGrid`.