---
title: "Overfitting"
output: html_document
---

```{r setup, include=FALSE}
library(tidymodels)
library(tidyverse)
library(MASS)
# install.packages("remotes")
# remotes::install_github("curso-r/treesnip")
library(treesnip)
```


```{r}
Boston
```

Base de Treino/Teste - Split inicial

```{r}
boston_split <- mc_cv(Boston, prop = 0.8, times = 1)
```

Modelo - algoritmo, modo e motor

```{r}
glimpse(MASS::Boston)
boston_model <- decision_tree(min_n = tune()) %>%
  set_mode("regression") %>%
  set_engine("tree")
```

```{r}
pars <- parameters(boston_model) %>% 
  update(min_n = dials::min_n(range = c(2, 150)))

#boston_split <- vfold_cv(MASS::Boston, v = 5)

boston_tune <- tune_grid(
  boston_model,
  medv ~ .,
  grid = grid_regular(pars, levels = 10),
  resamples = boston_split
)

autoplot(boston_tune)
```

```{r}
collect_metrics(boston_tune) %>% 
  ggplot(aes(x = min_n, y = mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err)) +
  facet_wrap(~.metric, scales = "free")
```


O melhor modelo

```{r}
boston_best <- select_best(boston_tune, metric = "rmse")
```

